// @generated by conformance/generate-corpus.mjs; do not edit.

use crate::Fixture;

#[rustfmt::skip]
pub(crate) static V1_FIXTURES: &[Fixture] = &[
    Fixture {
        name: "agent-completed-max-turns.json",
        raw_json: include_str!("../../../conformance/v1/agent-completed-max-turns.json"),
    },
    Fixture {
        name: "agent-completed-repeated-terminal.json",
        raw_json: include_str!("../../../conformance/v1/agent-completed-repeated-terminal.json"),
    },
    Fixture {
        name: "agent-completed.json",
        raw_json: include_str!("../../../conformance/v1/agent-completed.json"),
    },
    Fixture {
        name: "agent-started.json",
        raw_json: include_str!("../../../conformance/v1/agent-started.json"),
    },
    Fixture {
        name: "agent-text-truncated.json",
        raw_json: include_str!("../../../conformance/v1/agent-text-truncated.json"),
    },
    Fixture {
        name: "agent-text.json",
        raw_json: include_str!("../../../conformance/v1/agent-text.json"),
    },
    Fixture {
        name: "agent-tool-result-error.json",
        raw_json: include_str!("../../../conformance/v1/agent-tool-result-error.json"),
    },
    Fixture {
        name: "agent-tool-result-subagent.json",
        raw_json: include_str!("../../../conformance/v1/agent-tool-result-subagent.json"),
    },
    Fixture {
        name: "agent-tool-result.json",
        raw_json: include_str!("../../../conformance/v1/agent-tool-result.json"),
    },
    Fixture {
        name: "agent-tool-use-subagent.json",
        raw_json: include_str!("../../../conformance/v1/agent-tool-use-subagent.json"),
    },
    Fixture {
        name: "agent-tool-use.json",
        raw_json: include_str!("../../../conformance/v1/agent-tool-use.json"),
    },
    Fixture {
        name: "agent-warning.json",
        raw_json: include_str!("../../../conformance/v1/agent-warning.json"),
    },
    Fixture {
        name: "control-applied-interrupt.json",
        raw_json: include_str!("../../../conformance/v1/control-applied-interrupt.json"),
    },
    Fixture {
        name: "control-applied-not-live.json",
        raw_json: include_str!("../../../conformance/v1/control-applied-not-live.json"),
    },
    Fixture {
        name: "control-requested-interrupt.json",
        raw_json: include_str!("../../../conformance/v1/control-requested-interrupt.json"),
    },
    Fixture {
        name: "control-requested-steer.json",
        raw_json: include_str!("../../../conformance/v1/control-requested-steer.json"),
    },
    Fixture {
        name: "decision-answered-excuse-requested-run.json",
        raw_json: include_str!("../../../conformance/v1/decision-answered-excuse-requested-run.json"),
    },
    Fixture {
        name: "decision-answered-excuse.json",
        raw_json: include_str!("../../../conformance/v1/decision-answered-excuse.json"),
    },
    Fixture {
        name: "decision-requested-budget.json",
        raw_json: include_str!("../../../conformance/v1/decision-requested-budget.json"),
    },
    Fixture {
        name: "decision-requested-gate-inconclusive.json",
        raw_json: include_str!("../../../conformance/v1/decision-requested-gate-inconclusive.json"),
    },
    Fixture {
        name: "decision-requested-human-decides-options.json",
        raw_json: include_str!("../../../conformance/v1/decision-requested-human-decides-options.json"),
    },
    Fixture {
        name: "decision-requested-human-decides.json",
        raw_json: include_str!("../../../conformance/v1/decision-requested-human-decides.json"),
    },
    Fixture {
        name: "decision-requested-tripwire.json",
        raw_json: include_str!("../../../conformance/v1/decision-requested-tripwire.json"),
    },
    Fixture {
        name: "decision-requested-unclassified.json",
        raw_json: include_str!("../../../conformance/v1/decision-requested-unclassified.json"),
    },
    Fixture {
        name: "decision-requested-unexplained-write.json",
        raw_json: include_str!("../../../conformance/v1/decision-requested-unexplained-write.json"),
    },
];
