#!/usr/bin/env node

import { readFile, readdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const repositoryRoot = fileURLToPath(new URL("../", import.meta.url));
const corpusDirectory = path.join(repositoryRoot, "conformance/v1");
const rustOutput = path.join(
  repositoryRoot,
  "crates/ethogram-corpus/src/corpus.rs",
);
const typescriptOutput = path.join(
  repositoryRoot,
  "packages/ethogram-corpus/src/corpus.ts",
);
const utf8Decoder = new TextDecoder("utf-8", {
  fatal: true,
  ignoreBOM: true,
});

const entries = await readdir(corpusDirectory, { withFileTypes: true });
const fixtureNames = entries
  .filter((entry) => entry.isFile() && entry.name.endsWith(".json"))
  .map((entry) => entry.name)
  .sort((left, right) =>
    Buffer.compare(Buffer.from(left, "utf8"), Buffer.from(right, "utf8")),
  );

const fixtures = await Promise.all(
  fixtureNames.map(async (name) => ({
    name,
    rawJson: utf8Decoder.decode(await readFile(path.join(corpusDirectory, name))),
  })),
);

function rustString(value) {
  let literal = '"';
  for (const scalar of value) {
    switch (scalar) {
      case '"':
        literal += '\\"';
        break;
      case "\\":
        literal += "\\\\";
        break;
      case "\n":
        literal += "\\n";
        break;
      case "\r":
        literal += "\\r";
        break;
      case "\t":
        literal += "\\t";
        break;
      default: {
        const codePoint = scalar.codePointAt(0);
        if (codePoint < 0x20 || codePoint === 0x7f) {
          literal += `\\u{${codePoint.toString(16)}}`;
        } else {
          literal += scalar;
        }
      }
    }
  }
  return `${literal}"`;
}

const rustEntries = fixtures
  .map(
    ({ name }) => `    Fixture {
        name: ${rustString(name)},
        raw_json: include_str!(${rustString(`../../../conformance/v1/${name}`)}),
    },`,
  )
  .join("\n");
const rustSource = `// @generated by conformance/generate-corpus.mjs; do not edit.

use crate::Fixture;

pub(crate) static V1_FIXTURES: &[Fixture] = &[${rustEntries ? `\n${rustEntries}\n` : ""}];
`;

const typescriptEntries = fixtures
  .map(
    ({ name, rawJson }) => `  {
    name: ${JSON.stringify(name)},
    rawJson: ${JSON.stringify(rawJson)},
  },`,
  )
  .join("\n");
const typescriptSource = `// @generated by conformance/generate-corpus.mjs; do not edit.

export const V1_FIXTURES = [${typescriptEntries ? `\n${typescriptEntries}\n` : ""}] as const;
`;

await Promise.all([
  writeFile(rustOutput, rustSource, "utf8"),
  writeFile(typescriptOutput, typescriptSource, "utf8"),
]);

console.log(
  `Generated Rust and TypeScript views of ${fixtures.length} v1 fixture${fixtures.length === 1 ? "" : "s"}.`,
);
